# CI workflow for testing the provisioning system and other components
name: CI

on:
  push:
    branches: [ main, feature/* ]
  pull_request:
    branches: [ main ]

jobs:
  test-kohya-config:
    runs-on: ubuntu-latest
    
    steps:
    - name: Check out the repository's code
      uses: actions/checkout@v4
      
    - name: Install uv
      uses: astral-sh/setup-uv@v4
      with:
        version: "latest"
        
    - name: Validate TOML configurations
      run: |
        # Install tomli to test TOML parsing
        uv run --with tomli python -c "
        import tomli
        import os
        import glob
        
        # Test all example TOML files
        for toml_file in glob.glob('examples/*.toml'):
            print(f'Validating {toml_file}')
            with open(toml_file, 'rb') as f:
                try:
                    config = tomli.load(f)
                    print(f'✅ {toml_file} is valid')
                except Exception as e:
                    print(f'❌ {toml_file} failed: {e}')
                    exit(1)
        print('All TOML files are valid!')
        "
        
    - name: Test workspace structure
      run: |
        # Create test workspace with Kohya SS structure
        mkdir -p /tmp/test-workspace/kohya_ss/{models,dataset,outputs,logs,reg,config}
        mkdir -p /tmp/test-workspace/logs
        
        # Verify structure
        ls -la /tmp/test-workspace/kohya_ss/
        echo "Kohya SS workspace structure validated"

  lint-dockerfile:
    runs-on: ubuntu-latest
    
    steps:
    - name: Check out the repository's code
      uses: actions/checkout@v4
      
    - name: Lint Dockerfile
      uses: hadolint/hadolint-action@v3.1.0
      with:
        dockerfile: Dockerfile
        failure-threshold: warning